config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "posts#index"

  # REVIEW: 3
  get "posts/index" => "posts#index"
  get "posts/new" => "posts#new"
  post "posts/create" => "posts#create"
  get "posts/:id/show" => "posts#show"
  get "posts/:id/edit" => "posts#edit"
  post "posts/:id/update" => "posts#update"
  get "posts/:id/destroy" => "posts#destroy"

  post "posts/:id/comments" => "comments#create", as: "posts_comments_create"
  get "posts/:id/post_likes" => "post_likes#create"
  get "comments/:id/comment_likes" => "comment_likes#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  has_many :comment_likes, dependent: :destroy
  has_many :users, through: :comment_likes
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/post.rb
class Post < ApplicationRecord
  # REVIEW : 3 => validates
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :users, through: :post_likes

  mount_uploader :image, ImageUploader
end

app/models/post_like.rb
class PostLike < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  # REVIEW : 1 
  has_one :post_likes, dependent: :destroy
  has_one :comment_likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_likes_controller.rb
class CommentLikesController < ApplicationController
	# REVIEW : 3
	before_action :authenticate_user!, only: [:create]

	def create
		comment = Comment.find(params[:id])
		comment_like = CommentLike.find_by(comment_id: comment.id, user_id: current_user.id)

		if comment_like.present?
			comment_like.destroy
		else
			CommentLike.create(comment_id: comment.id, user_id: current_user.id)
		end

		redirect_back(fallback_location: root_path)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # REVIEW : 1
  def create
		post = Post.find(params[:id])

    comment = Comment.new
    comment.body = params[:body]
    # REVIEW : 3
    comment.post_id = post.id
		comment.user_id = current_user.id

    comment.save

		#comment = Comment.create(body: params[:body], post_id: post.id, user_id: current_user.id)

    #redirect_to request.referrer
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/post_likes_controller.rb
class PostLikesController < ApplicationController
	# REVIEW : 3
	before_action :authenticate_user!, only: [:create]
	def create
		post = Post.find(params[:id])
		post_like = PostLike.find_by(post_id: post.id, user_id: current_user.id)

		if post_like.present?
			post_like.destroy
		else
			PostLike.create(post_id: post.id, user_id: current_user.id)
		end

		redirect_back(fallback_location: root_path)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # REVIEW : 1
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
  end

  # REVIEW : 3
  def create
    @post = Post.new

    @post.title = params[:title]
    @post.content = params[:content]
    @post.user_id = current_user.id
    @post.image = params[:image]
    
    @post.save
    #post = Post.create(title: params[:title], content: params[:content], user_id: current_user.id, image: params[:image])

    redirect_to "/posts/#{@post.id}/show"
  end

  # REVIEW : 1
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(title: params[:title], content: params[:content])

    redirect_to "/posts/#{@post.id}/show"
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_likes_helper.rb
module CommentLikesHelper
end

app/helpers/post_likes_helper.rb
module PostLikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<form action="/posts/<%= @post.id %>/update" method="POST">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    글 : <input type="text" name="title" value="<%= @post.title %>">
    <br>
    내용 : <textarea name="content"> <%= @post.content %> </textarea>
    <br>
    <button type="submit">제출</button>
</form>

app/views/posts/index.html.erb
<% if user_signed_in? %>
    <a href="/my_page">마이페이지</a>
    <%= current_user.email %>님 안녕하세요!!
    <%= link_to "로그아웃", destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to "로그인", new_user_session_path %>
<% end %>
<hr>
<a href="/posts/new">새 글 쓰기</a>
<hr>

<% @posts.each do |post| %>
    title : <%= post.title %>
    content : <%= post.content %>
    <a href="/posts/<%= post.id %>/show">보기</a>
    <a href="/posts/<%= post.id %>/edit">수정</a>
	<a href="/posts/<%= post.id %>/destroy">삭제</a>
    <hr>
<% end %>

app/views/posts/new.html.erb
<%# REVIEW : 1  %>
<form action="/posts/create" method="POST">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    글 : <input type="text" name="title">
    <br>
    내용 : <textarea name="content"></textarea>
    <br>
    <input type="file" accept="image/*" name="image">
    <button type="submit">제출</button>
</form>
<a href="/posts/index">리스트로 이동</a>
<!-- 작성을 취소 할 떄에는 어떻게 하나? 단순하게 a태그로 이동만 시켜줘도 되나? -->

app/views/posts/show.html.erb
<%= @post.id %> 의 글
<hr>
title : <%= @post.title %>
<hr>
content : <%= @post.content %>
<hr>
<img src="<%= @post.image_url %>" alt="" class="">
<hr>
좋아요 수 : <%= @post.post_likes.count %>
<hr>
<a href="/posts/<%= @post.id %>/post_likes">좋아요</a>
<br>
<br>
<a href="/posts/index">리스트로 이동</a>
<br>
<br>
댓글 작성하기
<form action="<%= posts_comments_create_path(@post) %>" method="POST">
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	댓글 : <input type="text" name="body">
	<button type="submit">제출</button>
</form>
<hr>
<!-- 왜 액션을 "posts/<%#= post.id %>/comments" 넘기면 url주소가 posts/show/posts/id/comments로 넘어가지??? -->
댓글 보기
<hr>
<% Comment.where(post_id: @post.id).each do |comment| %>
	작성자 : <%= comment.user.email %>
	댓글 : <%= comment.body %>
	좋아요 수 : <%= comment.comment_likes.count %>
	<a href="/comments/<%= comment.id %>/comment_likes">좋아요</a>
	<hr>
<% end %>